layout_spectrum: 0.4375677
typography_spectrum: 0.5946983
color:
  saturation: 0.4749724
  lightness: 0.3841501
  brandStrength: 0.3732545
  brandColors:
    - '#020203'
    - '#6E4C30'
    - '#C6B39A'
    - '#FAE9CF'
    - '#FFFFFF'
  rhythmicContrast: 0.03826007
name: Scotoma
